### ISSUE TITLE
mark-next-like-this with no region sometimes doesn't place new cursor in the same column

### ISSUE THREAD

**Issue by DesiQuintans** [magnars/multiple-cursors.el#336]
Usually when I do `mark-next-like-this` without a selection, it will insert a cursor below the mark and in the same column, as intended. But other times (randomly, as far as I can tell), it puts the cursor a little forward in the subsequent lines:

The most recent time happened while I was in org-mode, partial text below (all headlines were folded, so the checkbox list in the middle was not editable). I had the cursor on the I in 'missing' (second line), no region selected, and keyed `mark-next-like-this` twice. I indicate the places where the cursors were created with square brackets:

```
*** TODO Submit to CRAN again                               :librarian:
*** TODO Impute m[i]ssing phenology info
*** TODO Pull phenology even[t]s from raw data:
- [ ] Start of 'Young' stage
- [ ] End of 'Ripe' stage
- [ ] Length of reproductive period (end of Ripe minus start of Young)
- [ ] The peaks of the waves of flowering and fruiting (when, and how many)

*** TODO Produce final 'phen['] dataframe.
```

**Comment by FlorianPerucki** [comment]
This happens to me also, it seems I can reproduce it with the following steps (cursor(s) location at |):

```
|foo
bar
```
Press C-n to get the pointer at the begining of "bar", then C-p to put it back where it was initially. Running `mc/mark-next-like-this` after that always gives me the following:
```
|foo
bar|
```

If I click instead of moving with C-n or C-p, or if I press C-g before running `mc/mark-next-like-this` I'll get the expected behavior:
```
|foo
|bar
```

FWIW I'm running version 20180406.1350

Thanks!

**Comment by landshark666** [comment]
I have this issue too (Ubuntu14, Emacs 26.1, MC 20180615.1218).

For me it's related to having `display-line-numbers-mode` enabled.  If I disable that, the problem goes away.

**Comment by DesiQuintans** [comment]
Interesting, I have

```
(column-number-mode t)
(setq-default display-line-numbers t)
```
